<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerThtqaS0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerThtqaS0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerThtqaS0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerThtqaS0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerThtqaS0\App_KernelDevDebugContainer([
    'container.build_hash' => 'ThtqaS0',
    'container.build_id' => '181da1e0',
    'container.build_time' => 1581524811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerThtqaS0');
